batch_size: 2048
img_size: 224
validation_batch_size: 256
num_tokens: 8192
mean: [ 0.485, 0.456, 0.406 ]
std: [ 0.229, 0.224, 0.225 ]
opt: adamw
momentum: 0.9
weight_decay: 0.05
sched: cosine
lr: 1.5e-3 # DeiT: 0.0005 * (batch_size / 512)
min_lr: 1e-5
warmup_lr: 1e-6
warmup_epochs: 10
train_interpolation: bicubic
epochs: 300
amp: true
clip_grad: 3.0
layer_scale_init_value: 0.1 # 1e-5 on Large
#CAE
decoder_layer_scale_init_value: 0.1
decoder_embed_dim: 384
decoder_num_heads: 6

# Augmentation arguments
scale: [ 1., 1. ]
ratio: [ 1., 1. ]
hflip: 0
vflip: 0
color_jitter: 0.4
aa: null # rand-m9-mstd0.5
reprob: 0 # 0.25
mixup: 0 # 0.8
cutmix: 0 # 1.0
smoothing: 0
drop: 0
drop_path: 0.1
